### ISSUE TITLE
AI Agent Fails to Identify Winning Move

### ISSUE THREAD

**Issue by jukha** [ehtishama/tictactoe_ai#1]
I  noticed an issue related to the behavior of the AI agent. When the human player has marked two consecutive cells, and it is the AI agent's turn to move, the agent fails to mark the third cell to prevent the human player from winning the game (images attached for these use cases for better understanding). While it is possible that this behavior was intentionally left out, I thought it would be helpful to bring it to your attention and suggest it as a possible improvement for future updates. It seems like the algorithm needs to be improved to identify and prioritize the winning moves to ensure a more realistic gameplay experience.

![Image description](https://i.imgur.com/pJB3REa.png)
![Image description](https://i.imgur.com/0utoehl.png)

Best regards,

**Comment by ehtishama** [comment]
Hi @jukha, thanks for going through it and pointing it out. I'll fix it soon.

**Comment by ehtishama** [comment]
I was wondering, if possible, would you like to write a fix for it? @jukha. I'll assign this issue to you if you're interested.

**Comment by jukha** [comment]
Although I'm not certain, I could try in my free time.
